name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  RunTests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate --ansi

      - name: Run Migrations
        run: php artisan migrate --seed

      - name: Run Unit Tests
        run: php artisan test --testsuite=Unit

      - name: Run Feature Tests
        run: php artisan test --testsuite=Feature

  Notify:
    name: Notify
    needs: [RunTests]
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: |
          php artisan app:send-notifications '{"TestResult": "${{ job.RunTests.status }}"}'
    