name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate --ansi

      - name: Run Migrations
        run: php artisan migrate --seed

      - name: Run Tests
        run: php artisan test
      
      - name: Notify
        run: php artisan app:send-notifications ${{ job.status }} "${{ github.event.head_commit.message }}"

